//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtekno.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastabilgi1
    {
        public int hastano { get; set; }
        public string hastaad { get; set; }
        public Nullable<int> yas { get; set; }
        public string cinsiyet { get; set; }
        public string hastalik { get; set; }
        public string ilac { get; set; }
    }
}
