//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtekno.Models.entity3
{
    using System;
    using System.Collections.Generic;
    
    public partial class doktorlar
    {
        public string doktorad { get; set; }
        public string doktorbrans { get; set; }
        public string unvan { get; set; }
    }
}
